// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/**
 * The store: one bucket per ModelDefinitions entry, typed with what it
 * holds, plus the two buses. `eventsHandler` is the typed change bus the
 * buckets broadcast on; `updatedHandler` emits the object type after any
 * write to its bucket (once per flush), for consumers that only need
 * "something in this bucket changed". `reset()` starts a new generation
 * and empties every bucket silently (the session reset: a reload follows).
 */
import { DataCacheIndex, type BucketContext } from "./DataCacheIndex";
import { DataEventHandler, EventHandler, type IndexValue, type ListenerErrorHandler } from "./EventHandler";
import { assertValidModelDefinitions, ModelDefinitions, type ModelDefinition } from "./ModelDefinitions";
import type { UserModel } from "../models/UserModel";
import type { CurrentUserModel } from "../models/CurrentUserModel";
import type { ProjectModel } from "../models/ProjectModel";
import type { TaskModel } from "../models/TaskModel";
import type { TagModel } from "../models/TagModel";

/** Rows of `comments`: no model class; only the declared key fields are typed. */
export interface CommentsRecord extends Record<string, unknown> {
  id: IndexValue;
  task_id?: IndexValue | null;
  author_id?: IndexValue | null;
}

/** Rows of `task_tags_relation`: no model class; only the declared key fields are typed. */
export interface TaskTagsRelationRecord extends Record<string, unknown> {
  id: IndexValue;
  task_id?: IndexValue | null;
  tag_id?: IndexValue | null;
}

export class DataCache {
  readonly eventsHandler: DataEventHandler;
  readonly updatedHandler: EventHandler<string>;
  /** Bumped by `reset()`; loaders compare it to drop responses that belong to a previous session. */
  generation = 0;
  private readonly buckets: ReadonlyMap<string, DataCacheIndex<object>>;

  readonly users: DataCacheIndex<UserModel>;
  readonly current_users: DataCacheIndex<CurrentUserModel>;
  readonly projects: DataCacheIndex<ProjectModel>;
  readonly tasks: DataCacheIndex<TaskModel>;
  readonly comments: DataCacheIndex<CommentsRecord>;
  readonly tags: DataCacheIndex<TagModel>;
  readonly task_tags_relation: DataCacheIndex<TaskTagsRelationRecord>;

  /** The buckets are generated for ModelDefinitions, so that is the only schema a DataCache can hold. */
  constructor(onListenerError?: ListenerErrorHandler) {
    assertValidModelDefinitions(ModelDefinitions);
    this.eventsHandler = new DataEventHandler(onListenerError);
    this.updatedHandler = new EventHandler<string>(onListenerError);
    const buckets = new Map<string, DataCacheIndex<object>>();
    const context: BucketContext = { events: this.eventsHandler, bucket: (objectType) => buckets.get(objectType), owner: this };
    const definitions: Record<string, ModelDefinition> = ModelDefinitions;
    this.users = new DataCacheIndex<UserModel>("users", definitions, context);
    buckets.set("users", this.users);
    this.current_users = new DataCacheIndex<CurrentUserModel>("current_users", definitions, context);
    buckets.set("current_users", this.current_users);
    this.projects = new DataCacheIndex<ProjectModel>("projects", definitions, context);
    buckets.set("projects", this.projects);
    this.tasks = new DataCacheIndex<TaskModel>("tasks", definitions, context);
    buckets.set("tasks", this.tasks);
    this.comments = new DataCacheIndex<CommentsRecord>("comments", definitions, context);
    buckets.set("comments", this.comments);
    this.tags = new DataCacheIndex<TagModel>("tags", definitions, context);
    buckets.set("tags", this.tags);
    this.task_tags_relation = new DataCacheIndex<TaskTagsRelationRecord>("task_tags_relation", definitions, context);
    buckets.set("task_tags_relation", this.task_tags_relation);
    this.buckets = buckets;
    for (const objectType of buckets.keys()) {
      this.eventsHandler.subscribe({ objectType }, () => this.updatedHandler.emit(objectType));
    }
  }

  /** Every bucket name, in definition order. */
  get objectTypes(): readonly string[] {
    return [...this.buckets.keys()];
  }

  /** The bucket for an object type named at runtime (push messages, generic loaders); typed buckets are the properties. */
  bucket(objectType: string): DataCacheIndex<object> | undefined {
    return this.buckets.get(objectType);
  }

  /** A new generation and empty buckets, without broadcasts: the session reset. */
  reset(): void {
    this.generation++;
    for (const bucket of this.buckets.values()) bucket.clear();
  }
}
