/**
 * The model generator: everything derived from `ModelDefinitions` is emitted
 * from here, never hand-maintained. Pure: `generateModels(definitions)`
 * returns the files as text; `scripts/generate-models.ts` writes them (or,
 * with `--check`, fails when the committed files differ). Deterministic: the
 * output depends only on the definitions map, in its own key order.
 *
 * Emitted:
 *
 *   src/store/DataCache.ts
 *     the store class: one typed `DataCacheIndex` per definition, the two
 *     buses, `generation` + `reset()`, and a `<Type>Record` interface for
 *     every definition without a model class (plain rows: only the declared
 *     key fields are typed).
 *
 *   src/models/appdata/<Model>AppData.ts       (per definition with `model`)
 *     the generated base of the handwritten model: `declare`d key fields
 *     (see PassiveModel for why `declare`) and the store accessors:
 *       foreignKeys        getX()    → other.getById(this.field)
 *       foreignKeysArray   getX()    → other.getMultipleByIds(this.field ?? [])
 *       relatedObjectType  getX()    → child.getGroupedById(key, this.<index>)
 *       hasMany            getX()    → this bucket's getAssociation(through, thisKey, otherKey, this.<index>)
 *       metaData           getKey()  → this bucket's getMetaData(this.<index>, key)
 *     Every accessor reads `storeOf(this)`: the store whose bucket holds the
 *     model (set on `add`), never a module-level singleton, so a model in a
 *     test's own DataCache resolves against that cache. No generated module
 *     imports AppDataFactory.
 *
 * Buckets and accessors are typed with the HANDWRITTEN model classes
 * (`src/models/<Model>.ts`, `export class <Model> extends <Model>AppData`),
 * imported as types only, so the generated code never depends on them at
 * runtime. The generator does not write those files: a definition whose
 * model file is missing fails `bun run check` (and the script warns).
 */
import type { ModelDefinition } from "../../store/ModelDefinitions";
import { assertValidModelDefinitions, metaDataGetterName, pascalCase, recordTypeName } from "../../store/ModelDefinitions";

export interface GeneratedFile {
  /** Repo-relative path. */
  readonly path: string;
  readonly content: string;
}

export const GENERATED_HEADER = "// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.";

const STORE_DIR = "src/store";
const MODELS_DIR = "src/models";
const APPDATA_DIR = "src/models/appdata";

/** Where the handwritten model class for `model` lives (the generator reads its type, never writes it). */
export function modelPath(model: string): string {
  return `${MODELS_DIR}/${model}.ts`;
}

/**
 * Directories the generator OWNS: every `*AppData.ts` file in them is
 * generated, so one the current schema does not produce is an orphan (a
 * renamed or removed model) that the script deletes or, with `--check`, flags.
 */
export const OWNED_DIRECTORIES: readonly string[] = [APPDATA_DIR];
export const OWNED_FILE_SUFFIX = "AppData.ts";

/** The TypeScript type of what a bucket stores: the handwritten model class, or a generated record interface. */
function elementTypeName(objectType: string, def: ModelDefinition): string {
  return def.model ?? recordTypeName(objectType);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

export function generateModels(definitions: Record<string, ModelDefinition>): GeneratedFile[] {
  assertValidModelDefinitions(definitions);
  const types = Object.keys(definitions);
  const defOf = (objectType: string): ModelDefinition => {
    const def = definitions[objectType];
    if (def === undefined) throw new TypeError(`generate: unknown object type "${objectType}"`); // unreachable after validation
    return def;
  };
  const element = (objectType: string) => elementTypeName(objectType, defOf(objectType));

  const files: GeneratedFile[] = [{ path: `${STORE_DIR}/DataCache.ts`, content: generateDataCache(types, defOf, element) }];
  for (const objectType of types) {
    const def = defOf(objectType);
    if (def.model !== undefined) files.push({ path: `${APPDATA_DIR}/${def.model}AppData.ts`, content: generateAppData(objectType, def, defOf, element) });
  }
  return files;
}

// ---------------------------------------------------------------------------
// DataCache.ts
// ---------------------------------------------------------------------------

function generateDataCache(types: readonly string[], defOf: (t: string) => ModelDefinition, element: (t: string) => string): string {
  const modelImports = types
    .filter((t) => defOf(t).model !== undefined)
    .map((t) => `import type { ${element(t)} } from "../models/${element(t)}";`);
  const records = types.filter((t) => defOf(t).model === undefined).map((t) => generateRecord(t, defOf(t), element(t)));
  const properties = types.map((t) => `  readonly ${t}: DataCacheIndex<${element(t)}>;`);
  const constructions = types.flatMap((t) => [
    `    this.${t} = new DataCacheIndex<${element(t)}>(${quote(t)}, definitions, context);`,
    `    buckets.set(${quote(t)}, this.${t});`,
  ]);

  return [
    GENERATED_HEADER,
    "/**",
    " * The store: one bucket per ModelDefinitions entry, typed with what it",
    " * holds, plus the two buses. `eventsHandler` is the typed change bus the",
    " * buckets broadcast on; `updatedHandler` emits the object type after any",
    " * write to its bucket (once per flush), for consumers that only need",
    ' * "something in this bucket changed". `reset()` starts a new generation',
    " * and empties every bucket silently (the session reset: a reload follows).",
    " */",
    'import { DataCacheIndex, type BucketContext } from "./DataCacheIndex";',
    'import { DataEventHandler, EventHandler, type IndexValue, type ListenerErrorHandler } from "./EventHandler";',
    'import { assertValidModelDefinitions, ModelDefinitions, type ModelDefinition } from "./ModelDefinitions";',
    ...modelImports,
    "",
    ...records,
    "export class DataCache {",
    "  readonly eventsHandler: DataEventHandler;",
    "  readonly updatedHandler: EventHandler<string>;",
    "  /** Bumped by `reset()`; loaders compare it to drop responses that belong to a previous session. */",
    "  generation = 0;",
    "  private readonly buckets: ReadonlyMap<string, DataCacheIndex<object>>;",
    "",
    ...properties,
    "",
    "  /** The buckets are generated for ModelDefinitions, so that is the only schema a DataCache can hold. */",
    "  constructor(onListenerError?: ListenerErrorHandler) {",
    "    assertValidModelDefinitions(ModelDefinitions);",
    "    this.eventsHandler = new DataEventHandler(onListenerError);",
    "    this.updatedHandler = new EventHandler<string>(onListenerError);",
    "    const buckets = new Map<string, DataCacheIndex<object>>();",
    "    const context: BucketContext = { events: this.eventsHandler, bucket: (objectType) => buckets.get(objectType), owner: this };",
    "    const definitions: Record<string, ModelDefinition> = ModelDefinitions;",
    ...constructions,
    "    this.buckets = buckets;",
    "    for (const objectType of buckets.keys()) {",
    "      this.eventsHandler.subscribe({ objectType }, () => this.updatedHandler.emit(objectType));",
    "    }",
    "  }",
    "",
    "  /** Every bucket name, in definition order. */",
    "  get objectTypes(): readonly string[] {",
    "    return [...this.buckets.keys()];",
    "  }",
    "",
    "  /** The bucket for an object type named at runtime (push messages, generic loaders); typed buckets are the properties. */",
    "  bucket(objectType: string): DataCacheIndex<object> | undefined {",
    "    return this.buckets.get(objectType);",
    "  }",
    "",
    "  /** A new generation and empty buckets, without broadcasts: the session reset. */",
    "  reset(): void {",
    "    this.generation++;",
    "    for (const bucket of this.buckets.values()) bucket.clear();",
    "  }",
    "}",
    "",
  ].join("\n");
}

function generateRecord(objectType: string, def: ModelDefinition, name: string): string {
  const fields = [`  ${def.index}: IndexValue;`];
  for (const field of Object.keys(def.foreignKeys ?? {})) if (field !== def.index) fields.push(`  ${field}?: IndexValue | null;`);
  for (const field of Object.keys(def.foreignKeysArray ?? {})) fields.push(`  ${field}?: readonly IndexValue[] | null;`);
  return [
    `/** Rows of \`${objectType}\`: no model class; only the declared key fields are typed. */`,
    `export interface ${name} extends Record<string, unknown> {`,
    ...fields,
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// <Model>AppData.ts
// ---------------------------------------------------------------------------

function generateAppData(objectType: string, def: ModelDefinition, defOf: (t: string) => ModelDefinition, element: (t: string) => string): string {
  const self = `${def.model}AppData`;
  const referenced = new Set<string>();
  const fields: string[] = [`  declare ${def.index}: IndexValue;`];
  const accessors: string[] = [];

  for (const [field, fk] of Object.entries(def.foreignKeys ?? {})) {
    if (field !== def.index) fields.push(`  declare ${field}?: IndexValue | null;`);
    referenced.add(fk.objectType);
    accessors.push(
      `  ${fk.getter}(): ${element(fk.objectType)} | undefined {`,
      `    return storeOf(this).${fk.objectType}.getById(this.${field});`,
      "  }",
    );
  }
  for (const [field, fk] of Object.entries(def.foreignKeysArray ?? {})) {
    fields.push(`  declare ${field}?: readonly IndexValue[] | null;`);
    referenced.add(fk.objectType);
    accessors.push(
      `  ${fk.getter}(): ${element(fk.objectType)}[] {`,
      `    return storeOf(this).${fk.objectType}.getMultipleByIds(this.${field} ?? []);`,
      "  }",
    );
  }
  for (const rel of Object.values(def.relatedObjectType ?? {})) {
    referenced.add(rel.objectType);
    accessors.push(
      `  ${rel.getter}(): readonly ${element(rel.objectType)}[] {`,
      `    return storeOf(this).${rel.objectType}.getGroupedById(${quote(rel.key)}, this.${def.index});`,
      "  }",
    );
  }
  for (const hm of Object.values(def.hasMany ?? {})) {
    referenced.add(hm.objectType);
    accessors.push(
      `  ${hm.getter}(): ${element(hm.objectType)}[] {`,
      `    return storeOf(this).${objectType}.getAssociation<${element(hm.objectType)}>(${quote(hm.through)}, ${quote(hm.thisKey)}, ${quote(hm.otherKey)}, this.${def.index});`,
      "  }",
    );
  }
  for (const key of def.metaData ?? []) {
    accessors.push(
      `  /** Side data attached with \`addMetaData\` under ${quote(key)}; \`undefined\` until it arrives. */`,
      `  ${metaDataGetterName(key)}(): unknown {`,
      `    return storeOf(this).${objectType}.getMetaData(this.${def.index}, ${quote(key)});`,
      "  }",
    );
  }

  const typeImports: string[] = [];
  const recordImports: string[] = [];
  // the model classes are the SUBCLASSES of these bases, so even a self-reference (getParent) is an import
  for (const other of [...referenced].sort()) {
    const name = element(other);
    if (defOf(other).model !== undefined) typeImports.push(`import type { ${name} } from "../${name}";`);
    else recordImports.push(name);
  }
  const cacheImport = `import type { DataCache${recordImports.map((name) => `, ${name}`).join("")} } from "../../store/DataCache";`;

  return [
    GENERATED_HEADER,
    `/** Generated base of \`${def.model}\` (ModelDefinitions.${objectType}): the declared key fields and the store accessors. */`,
    accessors.length > 0 ? 'import { PassiveModel, storeOf } from "../generator/PassiveModel";' : 'import { PassiveModel } from "../generator/PassiveModel";',
    cacheImport,
    'import type { IndexValue } from "../../store/EventHandler";',
    ...typeImports,
    "",
    `export class ${self} extends PassiveModel<DataCache> {`,
    ...fields,
    ...(accessors.length > 0 ? ["", ...accessors] : []),
    "}",
    "",
  ].join("\n");
}
