// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `CurrentUserModel` (ModelDefinitions.current_users): the declared key fields and the store accessors. */
import { PassiveModel } from "../generator/PassiveModel";
import { AppDataFactory } from "../../store/AppDataFactory";
import type { IndexValue } from "../../store/EventHandler";

export class CurrentUserModelAppData extends PassiveModel {
  declare id: IndexValue;

  /** Side data attached with `addMetaData`; `undefined` until it arrives. */
  get subscription(): unknown {
    return AppDataFactory.current_users.getMetaData(this.id, "subscription");
  }
}
