// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `CurrentUserModel` (ModelDefinitions.current_users): the declared key fields and the store accessors. */
import { PassiveModel, storeOf } from "../generator/PassiveModel";
import type { DataCache } from "../../store/DataCache";
import type { IndexValue } from "../../store/EventHandler";

export class CurrentUserModelAppData extends PassiveModel<DataCache> {
  declare id: IndexValue;

  /** Side data attached with `addMetaData` under "subscription"; `undefined` until it arrives. */
  getSubscription(): unknown {
    return storeOf(this).current_users.getMetaData(this.id, "subscription");
  }
}
