// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `ProjectModel` (ModelDefinitions.projects): the declared key fields and the store accessors. */
import { PassiveModel } from "../generator/PassiveModel";
import { AppDataFactory } from "../../store/AppDataFactory";
import type { IndexValue } from "../../store/EventHandler";
import type { TaskModelAppData } from "./TaskModelAppData";
import type { UserModelAppData } from "./UserModelAppData";

export class ProjectModelAppData extends PassiveModel {
  declare id: IndexValue;
  declare owner_id?: IndexValue | null;
  declare member_ids?: readonly IndexValue[] | null;

  getOwner(): UserModelAppData | undefined {
    return AppDataFactory.users.getById(this.owner_id);
  }
  getMembers(): UserModelAppData[] {
    return AppDataFactory.users.getMultipleByIds(this.member_ids ?? []);
  }
  getTasks(): readonly TaskModelAppData[] {
    return AppDataFactory.tasks.getGroupedById("project_id", this.id);
  }
}
