// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `ProjectModel` (ModelDefinitions.projects): the declared key fields and the store accessors. */
import { PassiveModel, storeOf } from "../generator/PassiveModel";
import type { DataCache } from "../../store/DataCache";
import type { IndexValue } from "../../store/EventHandler";
import type { TaskModel } from "../TaskModel";
import type { UserModel } from "../UserModel";

export class ProjectModelAppData extends PassiveModel<DataCache> {
  declare id: IndexValue;
  declare owner_id?: IndexValue | null;
  declare member_ids?: readonly IndexValue[] | null;

  getOwner(): UserModel | undefined {
    return storeOf(this).users.getById(this.owner_id);
  }
  getMembers(): UserModel[] {
    return storeOf(this).users.getMultipleByIds(this.member_ids ?? []);
  }
  getTasks(): readonly TaskModel[] {
    return storeOf(this).tasks.getGroupedById("project_id", this.id);
  }
}
