// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `TagModel` (ModelDefinitions.tags): the declared key fields and the store accessors. */
import { PassiveModel } from "../generator/PassiveModel";
import { AppDataFactory } from "../../store/AppDataFactory";
import type { IndexValue } from "../../store/EventHandler";
import type { TaskTagsRelationRecord } from "../../store/DataCache";
import type { TaskModelAppData } from "./TaskModelAppData";

export class TagModelAppData extends PassiveModel {
  declare id: IndexValue;

  getTaskLinks(): readonly TaskTagsRelationRecord[] {
    return AppDataFactory.task_tags_relation.getGroupedById("tag_id", this.id);
  }
  getTasks(): TaskModelAppData[] {
    return AppDataFactory.tags.getAssociation<TaskModelAppData>("task_tags_relation", "tag_id", "task_id", this.id);
  }
}
