// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `TagModel` (ModelDefinitions.tags): the declared key fields and the store accessors. */
import { PassiveModel, storeOf } from "../generator/PassiveModel";
import type { DataCache, TaskTagsRelationRecord } from "../../store/DataCache";
import type { IndexValue } from "../../store/EventHandler";
import type { TaskModelAppData } from "./TaskModelAppData";

export class TagModelAppData extends PassiveModel<DataCache> {
  declare id: IndexValue;

  getTaskLinks(): readonly TaskTagsRelationRecord[] {
    return storeOf(this).task_tags_relation.getGroupedById("tag_id", this.id);
  }
  getTasks(): TaskModelAppData[] {
    return storeOf(this).tags.getAssociation<TaskModelAppData>("task_tags_relation", "tag_id", "task_id", this.id);
  }
}
