// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `TaskModel` (ModelDefinitions.tasks): the declared key fields and the store accessors. */
import { PassiveModel } from "../generator/PassiveModel";
import { AppDataFactory } from "../../store/AppDataFactory";
import type { IndexValue } from "../../store/EventHandler";
import type { CommentsRecord, TaskTagsRelationRecord } from "../../store/DataCache";
import type { ProjectModelAppData } from "./ProjectModelAppData";
import type { TagModelAppData } from "./TagModelAppData";
import type { UserModelAppData } from "./UserModelAppData";

export class TaskModelAppData extends PassiveModel {
  declare id: IndexValue;
  declare project_id?: IndexValue | null;
  declare assignee_id?: IndexValue | null;

  getProject(): ProjectModelAppData | undefined {
    return AppDataFactory.projects.getById(this.project_id);
  }
  getAssignee(): UserModelAppData | undefined {
    return AppDataFactory.users.getById(this.assignee_id);
  }
  getComments(): readonly CommentsRecord[] {
    return AppDataFactory.comments.getGroupedById("task_id", this.id);
  }
  getTagLinks(): readonly TaskTagsRelationRecord[] {
    return AppDataFactory.task_tags_relation.getGroupedById("task_id", this.id);
  }
  getTags(): TagModelAppData[] {
    return AppDataFactory.tasks.getAssociation<TagModelAppData>("task_tags_relation", "task_id", "tag_id", this.id);
  }
}
