// GENERATED by scripts/generate-models.ts from src/store/ModelDefinitions.ts — DO NOT EDIT. Run `bun run generate-models`.
/** Generated base of `UserModel` (ModelDefinitions.users): the declared key fields and the store accessors. */
import { PassiveModel } from "../generator/PassiveModel";
import type { DataCache } from "../../store/DataCache";
import type { IndexValue } from "../../store/EventHandler";

export class UserModelAppData extends PassiveModel<DataCache> {
  declare id: IndexValue;
}
